left:
    position:
    x:     0 
    y:      -0.5 
    z:   1.0
    orientation:
    r:    0.0
    p:   0.0
    y:  0.0
right:
    position:
    x:     0 
    y:      0.5 
    z:   1.0
    orientation:
    r:    0.0
    p:   0.0
    y:  0.0